name: docker-test
     
on:
  push:
    branches: [ "vcpkg" ]
  pull_request:
    branches: [ "vcpkg" ]

jobs:
      
  test:
    #  needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build docker images
      run: docker build -t journal-cli -f Dockerfile .
    - name: Test image
      run: docker run --rm journal-cli --test
