name: docker-test
     
on:
  pull_request:
    branches: [ "main" ]

jobs:
      
  test:
    #  needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build docker images
      run: docker build -t review -f Dockerfile .
    - name: Test image
      run: docker run --rm --entrypoint /app/review-test review --journal
