name: docker-test
     
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  #    run: docker build -t journal-cli:$(date +%s) -f Dockerfile .
      
  test:
    #  needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build docker images
      run: DATE=$(date +%s) && docker build -t journal-cli:$DATE -f Dockerfile .
    - name: Test image
      run: docker run journal-cli:$DATE --test
    #- name: Run image
    #  run: docker run journal-cli
    #- name: Stop process
    #  run: PID=$! && \
    #    sleep 2 && \
    #    kill -INT $PID /
