name: build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    #steps:
    #- name: Checkout
    #  uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag test/journal-cli:$(date +%s)
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build docker images
      run: docker build -t local -f Dockerfile .
    - name: Run tests
      run: docker run -v $PWD:/srv -w/srv local
      
  #test:
   # needs: build
    #runs-on: ubuntu-latest

    #steps:
    #- uses: ./
    #- name: Test the app inside the docker image
    #  run: docker run journal-cli
