name: build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag journal-cli:$(date +%s)
    - name: Run the Docker image
      run: docker run --name test -i journal-cli
      
  #test:
   # needs: build
    #runs-on: ubuntu-latest

    #steps:
    #- uses: ./
    #- name: Test the app inside the docker image
    #  run: docker run journal-cli
